// Staged recipe facts, not loaded by the website. Full 20-record batch required before release.
const i=(amount,unit,name)=>({amount,unit,name});
module.exports=[
 {id:'meal-3',status:'sourced',variant:'Tavada anne köftesi',source:'https://yemek.com/tarif/anne-koftesi/',yieldPeople:4,yieldLabel:'4 kişilik',prep:45,cook:20,time:null,extraPrep:true,cal:412,waitLabel:'En az 30 dakika buzdolabında dinlendirme; başlıktaki hazırlık süresine dahil olup olmadığı açık değil',note:'Kaynak 45 dakika hazırlık ve 20 dakika pişirme verir. Dinlendirme dahil toplam süre belirsiz olduğundan süreli filtrelere alınmaz. Köfte baharatı isteğe bağlıdır. Kalori kaynak porsiyon tahminidir.',ingredients:[i(600,'gram','orta yağlı dana kıyma'),i(1,'adet','yumurta'),i(1,'adet','orta boy kuru soğan'),i(2,'dilim','bayat ekmek içi'),i(2,'yemek kaşığı','süt'),i(1,'diş','sarımsak'),i(.25,'demet','maydanoz'),i(1,'çay kaşığı','tuz'),i(1,'çay kaşığı','karabiber'),i(.5,'çay kaşığı','kimyon'),i(.5,'çay kaşığı','köfte baharatı (isteğe bağlı)'),i(4,'yemek kaşığı','ayçiçek yağı (kızartmak için)')]},
 {id:'meal-11',status:'sourced',variant:'Tencerede etli nohut',source:'https://www.lezzet.com.tr/yemek-tarifleri/diger-tarifler/baklagil-ve-tahilli-yemekler/etli-nohut-yemegi-tarifi',yieldPeople:6,yieldLabel:'6 kişilik',prep:20,cook:45,time:null,extraPrep:true,cal:420,waitLabel:'Geceden ıslatma ve ön haşlama gerekiyor; haşlama süresi kaynakta belirtilmemiş',note:'Kaynak nohudu geceden ıslatılmış olarak ölçülendiriyor. Ön haşlama suyu ayrıca gerekir; miktarı belirtilmemiştir. 20+45 dakika tüm ön hazırlıkları kapsamaz. Kalori kaynağın yaklaşık porsiyon değeridir.',ingredients:[i(2,'su bardağı','nohut (geceden ıslatılmış)'),i(300,'gram','kuşbaşı dana eti'),i(1,'adet','büyük boy soğan'),i(2,'yemek kaşığı','sıvı yağ'),i(1,'yemek kaşığı','tereyağı'),i(1,'yemek kaşığı','domates salçası'),i(1,'çay kaşığı','tuz'),i(.5,'çay kaşığı','karabiber'),i(1,'çay kaşığı','pul biber (isteğe bağlı)'),i([3,4],'su bardağı','sıcak su veya et suyu'),'ıslatma ve ön haşlama için su (miktar kaynakta belirtilmemiş)']},
 {id:'meal-86',status:'sourced',variant:'Kuşbaşı tavuk göğüslü bulgur pilavı',source:'https://www.lezzet.com.tr/yemek-tarifleri/pilav-ve-makarna-tarifleri/pilav-tarifleri/tavuklu-bulgur-pilavi-tarifi',yieldPeople:4,yieldLabel:'4 kişilik',prep:15,cook:30,time:55,extraPrep:true,cal:350,waitLabel:'10 dakika demlenme toplam 55 dakikaya eklendi',note:'Toplam: kaynakta 15 dakika hazırlık + 30 dakika pişirme + adımlardaki 10 dakika demlenme. Çiğ kuşbaşı tavuk doğrudan sotelenir; ayrı ön haşlama yoktur. Tuz, karabiber ve taze soğanın miktarı kaynakta belirtilmemiştir. Süre ve kalori yaklaşıktır.',ingredients:[i(2,'su bardağı','pilavlık bulgur'),i([300,350],'gram','kuşbaşı tavuk göğsü'),i(1,'adet','orta boy soğan'),i(2,'yemek kaşığı','tereyağı veya sıvı yağ'),i(3,'su bardağı','tavuk suyu veya su'),i(1,'adet','yeşil biber'),i(1,'adet','domates'),i(1,'çay kaşığı','pul biber veya kekik'),'tuz (damak tadına göre; kaynak ölçü vermiyor)','karabiber (damak tadına göre; kaynak ölçü vermiyor)','taze soğan (üzeri için; kaynak ölçü vermiyor)']},
 {id:'meal-121',status:'sourced',variant:'Fırında beşamel soslu karnabahar',source:'https://yemek.com/tarif/firinda-besamel-soslu-karnabahar/',yieldPeople:4,yieldLabel:'4 kişilik',prep:10,cook:30,time:null,extraPrep:true,cal:null,waitLabel:'Ön haşlama ve son kızartma süreleri kaynakta belirtilmemiş; toplam süre kesin değil',note:'Başlıkta 10 dakika hazırlık ve 30 dakika pişirme var. Adımlarda haşlama, 15 dakika fırın ve peynir eklendikten sonra yeniden kızartma bulunuyor. Eksik süreler nedeniyle süreli filtrelere alınmaz. Kalori kaynağı yok.',ingredients:[i(1,'adet','küçük boy karnabahar'),i(1,'su bardağı','rendelenmiş kaşar peyniri'),i(1,'yemek kaşığı','tereyağı'),i(1,'yemek kaşığı','un'),i(1,'su bardağı','süt'),i(1,'çay kaşığı','tuz'),i(.5,'çay kaşığı','karabiber'),'karnabaharı haşlamak için su (kaynak ölçü vermiyor)']}
 ,{id:'meal-151',status:'sourced',variant:'Izgara hindi göğüs',source:'https://yemek.com/tarif/izgara-hindi-gogus/',yieldPeople:1,yieldLabel:'1 kişilik',prep:15,cook:15,time:null,extraPrep:true,cal:276,waitLabel:'Sosladıktan sonra bekletme var; kaynak süresini belirtmiyor',note:'Kaynak 15 dakika hazırlık ve 15 dakika pişirme verir; marinasyon beklemesi belirsiz olduğundan süreli seçimlere alınmaz. Kalori kaynağın yaklaşık kişi başı değeridir.',ingredients:[i(250,'gram','hindi göğüs'),i(1,'yemek kaşığı','zeytinyağı'),i(1,'tutam','tuz'),i(1,'tutam','karabiber'),i(1,'tutam','tatlı toz biber'),i(1,'dal','taze biberiye'),i(2,'diş','sarımsak')]}
].map(recipe=>({...recipe,checkedAt:'2026-09-09'}));
